LIBRARY = jecsys
OBJDIR = obj
DEPDIR = $(OBJDIR)/dep
SRCDIR = src
INCDIR = interface

include $(SKFlat_WD)/external/jecsys/CondFormats/JetMETObjects/makefile.common

#INCLUDES += -I/cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_10_4_0_patch1/src
INCLUDES += -I$(SKFlat_WD)/external/jecsys/
